# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import product_pb2 as product__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in product_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCategory = channel.unary_unary(
                '/product_v1.ProductService/CreateCategory',
                request_serializer=product__pb2.CreateCategoryRequest.SerializeToString,
                response_deserializer=product__pb2.CategoryResponse.FromString,
                _registered_method=True)
        self.UpdateCategory = channel.unary_unary(
                '/product_v1.ProductService/UpdateCategory',
                request_serializer=product__pb2.UpdateCategoryRequest.SerializeToString,
                response_deserializer=product__pb2.CategoryResponse.FromString,
                _registered_method=True)
        self.GetCategory = channel.unary_unary(
                '/product_v1.ProductService/GetCategory',
                request_serializer=product__pb2.GetCategoryRequest.SerializeToString,
                response_deserializer=product__pb2.CategoryResponse.FromString,
                _registered_method=True)
        self.ListCategory = channel.unary_unary(
                '/product_v1.ProductService/ListCategory',
                request_serializer=product__pb2.ListCategoryRequest.SerializeToString,
                response_deserializer=product__pb2.ListCategoryResponse.FromString,
                _registered_method=True)
        self.DeleteCategory = channel.unary_unary(
                '/product_v1.ProductService/DeleteCategory',
                request_serializer=product__pb2.DeleteCategoryRequest.SerializeToString,
                response_deserializer=product__pb2.DeleteCategoryResponse.FromString,
                _registered_method=True)
        self.CreateProduct = channel.unary_unary(
                '/product_v1.ProductService/CreateProduct',
                request_serializer=product__pb2.CreateProductRequest.SerializeToString,
                response_deserializer=product__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.GetProduct = channel.unary_unary(
                '/product_v1.ProductService/GetProduct',
                request_serializer=product__pb2.GetProductRequest.SerializeToString,
                response_deserializer=product__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.UpdateProduct = channel.unary_unary(
                '/product_v1.ProductService/UpdateProduct',
                request_serializer=product__pb2.UpdateProductRequest.SerializeToString,
                response_deserializer=product__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.DeleteProduct = channel.unary_unary(
                '/product_v1.ProductService/DeleteProduct',
                request_serializer=product__pb2.DeleteProductRequest.SerializeToString,
                response_deserializer=product__pb2.DeleteProductResponse.FromString,
                _registered_method=True)
        self.ListProducts = channel.unary_unary(
                '/product_v1.ProductService/ListProducts',
                request_serializer=product__pb2.ListProductsRequest.SerializeToString,
                response_deserializer=product__pb2.ListProductsResponse.FromString,
                _registered_method=True)
        self.CreateAddOn = channel.unary_unary(
                '/product_v1.ProductService/CreateAddOn',
                request_serializer=product__pb2.CreateAddOnRequest.SerializeToString,
                response_deserializer=product__pb2.AddOnResponse.FromString,
                _registered_method=True)
        self.GetAddOn = channel.unary_unary(
                '/product_v1.ProductService/GetAddOn',
                request_serializer=product__pb2.GetAddOnRequest.SerializeToString,
                response_deserializer=product__pb2.AddOnResponse.FromString,
                _registered_method=True)
        self.UpdateAddOn = channel.unary_unary(
                '/product_v1.ProductService/UpdateAddOn',
                request_serializer=product__pb2.UpdateAddOnRequest.SerializeToString,
                response_deserializer=product__pb2.AddOnResponse.FromString,
                _registered_method=True)
        self.DeleteAddOn = channel.unary_unary(
                '/product_v1.ProductService/DeleteAddOn',
                request_serializer=product__pb2.DeleteAddOnRequest.SerializeToString,
                response_deserializer=product__pb2.DeleteAddOnResponse.FromString,
                _registered_method=True)
        self.ListAddOn = channel.unary_unary(
                '/product_v1.ProductService/ListAddOn',
                request_serializer=product__pb2.ListAddOnRequest.SerializeToString,
                response_deserializer=product__pb2.ListAddOnResponse.FromString,
                _registered_method=True)


class ProductServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProduct(self, request, context):
        """Products
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAddOn(self, request, context):
        """Add-ons
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAddOn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAddOn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAddOn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAddOn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCategory,
                    request_deserializer=product__pb2.CreateCategoryRequest.FromString,
                    response_serializer=product__pb2.CategoryResponse.SerializeToString,
            ),
            'UpdateCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCategory,
                    request_deserializer=product__pb2.UpdateCategoryRequest.FromString,
                    response_serializer=product__pb2.CategoryResponse.SerializeToString,
            ),
            'GetCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCategory,
                    request_deserializer=product__pb2.GetCategoryRequest.FromString,
                    response_serializer=product__pb2.CategoryResponse.SerializeToString,
            ),
            'ListCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCategory,
                    request_deserializer=product__pb2.ListCategoryRequest.FromString,
                    response_serializer=product__pb2.ListCategoryResponse.SerializeToString,
            ),
            'DeleteCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCategory,
                    request_deserializer=product__pb2.DeleteCategoryRequest.FromString,
                    response_serializer=product__pb2.DeleteCategoryResponse.SerializeToString,
            ),
            'CreateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProduct,
                    request_deserializer=product__pb2.CreateProductRequest.FromString,
                    response_serializer=product__pb2.ProductResponse.SerializeToString,
            ),
            'GetProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProduct,
                    request_deserializer=product__pb2.GetProductRequest.FromString,
                    response_serializer=product__pb2.ProductResponse.SerializeToString,
            ),
            'UpdateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProduct,
                    request_deserializer=product__pb2.UpdateProductRequest.FromString,
                    response_serializer=product__pb2.ProductResponse.SerializeToString,
            ),
            'DeleteProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProduct,
                    request_deserializer=product__pb2.DeleteProductRequest.FromString,
                    response_serializer=product__pb2.DeleteProductResponse.SerializeToString,
            ),
            'ListProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProducts,
                    request_deserializer=product__pb2.ListProductsRequest.FromString,
                    response_serializer=product__pb2.ListProductsResponse.SerializeToString,
            ),
            'CreateAddOn': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAddOn,
                    request_deserializer=product__pb2.CreateAddOnRequest.FromString,
                    response_serializer=product__pb2.AddOnResponse.SerializeToString,
            ),
            'GetAddOn': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAddOn,
                    request_deserializer=product__pb2.GetAddOnRequest.FromString,
                    response_serializer=product__pb2.AddOnResponse.SerializeToString,
            ),
            'UpdateAddOn': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAddOn,
                    request_deserializer=product__pb2.UpdateAddOnRequest.FromString,
                    response_serializer=product__pb2.AddOnResponse.SerializeToString,
            ),
            'DeleteAddOn': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAddOn,
                    request_deserializer=product__pb2.DeleteAddOnRequest.FromString,
                    response_serializer=product__pb2.DeleteAddOnResponse.SerializeToString,
            ),
            'ListAddOn': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAddOn,
                    request_deserializer=product__pb2.ListAddOnRequest.FromString,
                    response_serializer=product__pb2.ListAddOnResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'product_v1.ProductService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('product_v1.ProductService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product_v1.ProductService/CreateCategory',
            product__pb2.CreateCategoryRequest.SerializeToString,
            product__pb2.CategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product_v1.ProductService/UpdateCategory',
            product__pb2.UpdateCategoryRequest.SerializeToString,
            product__pb2.CategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product_v1.ProductService/GetCategory',
            product__pb2.GetCategoryRequest.SerializeToString,
            product__pb2.CategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product_v1.ProductService/ListCategory',
            product__pb2.ListCategoryRequest.SerializeToString,
            product__pb2.ListCategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product_v1.ProductService/DeleteCategory',
            product__pb2.DeleteCategoryRequest.SerializeToString,
            product__pb2.DeleteCategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product_v1.ProductService/CreateProduct',
            product__pb2.CreateProductRequest.SerializeToString,
            product__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product_v1.ProductService/GetProduct',
            product__pb2.GetProductRequest.SerializeToString,
            product__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product_v1.ProductService/UpdateProduct',
            product__pb2.UpdateProductRequest.SerializeToString,
            product__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product_v1.ProductService/DeleteProduct',
            product__pb2.DeleteProductRequest.SerializeToString,
            product__pb2.DeleteProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product_v1.ProductService/ListProducts',
            product__pb2.ListProductsRequest.SerializeToString,
            product__pb2.ListProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAddOn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product_v1.ProductService/CreateAddOn',
            product__pb2.CreateAddOnRequest.SerializeToString,
            product__pb2.AddOnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAddOn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product_v1.ProductService/GetAddOn',
            product__pb2.GetAddOnRequest.SerializeToString,
            product__pb2.AddOnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAddOn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product_v1.ProductService/UpdateAddOn',
            product__pb2.UpdateAddOnRequest.SerializeToString,
            product__pb2.AddOnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAddOn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product_v1.ProductService/DeleteAddOn',
            product__pb2.DeleteAddOnRequest.SerializeToString,
            product__pb2.DeleteAddOnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAddOn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product_v1.ProductService/ListAddOn',
            product__pb2.ListAddOnRequest.SerializeToString,
            product__pb2.ListAddOnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
