# Generated by Django 5.1.1 on 2025-03-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='Cart UUID'),
        ),
    ]
