# Generated by Django 5.1.1 on 2025-03-30 12:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_order_cart_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='add_ons_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Add On Total'),
        ),
    ]
