# Generated by Django 5.1.1 on 2025-03-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_type',
            field=models.CharField(choices=[('ORDER_TYPE_UNSPECIFIED', 'ORDER_TYPE_UNSPECIFIED'), ('ORDER_TYPE_DINE_IN', 'ORDER_TYPE_DINE_IN'), ('ORDER_TYPE_TAKE_AWAY', 'ORDER_TYPE_TAKE_AWAY'), ('ORDER_TYPE_DRIVE_THRU', 'ORDER_TYPE_DRIVE_THRU')], default='ORDER_TYPE_DINE_IN', max_length=30, verbose_name='Order type'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='state',
            field=models.CharField(choices=[('UNSPECIFIED_STATE', 'Unspecified_State'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='ACTIVE', max_length=30, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('UNSPCIFIED_DISCOUNT', 'UNSPCIFIED_DISCOUNT'), ('FIXED_DISCOUNT', 'FIXED_DISCOUNT'), ('PERCENTAGE_DISCOUNT', 'PERCENTAGE_DISCOUNT')], default='PERCENTAGE_DISCOUNT', max_length=30),
        ),
    ]
