# Generated by Django 5.1.1 on 2025-03-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cart_order_type_alter_cart_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='state',
            field=models.CharField(choices=[('CART_STATE_UNSPECIFIED_STATE', 'Unspecified_State'), ('CART_STATE_ACTIVE', 'Active'), ('CART_STATE_LOCKED', 'Completed'), ('CART_STATE_ABANDONED', 'Abandoned')], default='CART_STATE_ACTIVE', max_length=30, verbose_name='State'),
        ),
    ]
