# Generated by Django 5.1.1 on 2025-03-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cart_state'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='couponusage',
            name='api_couponu_user_ph_80eb7b_idx',
        ),
        migrations.RenameField(
            model_name='couponusage',
            old_name='order_uuid',
            new_name='cart_uuid',
        ),
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together={('coupon', 'user_phone_no', 'cart_uuid')},
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['user_phone_no', 'coupon', 'cart_uuid'], name='api_couponu_user_ph_2b988a_idx'),
        ),
    ]
