# Generated by Django 5.1.1 on 2025-03-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_couponusage_api_couponu_user_ph_80eb7b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='speacial_instructions',
        ),
        migrations.AddField(
            model_name='cart',
            name='special_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='special instructions'),
        ),
    ]
