# Generated by Django 5.1.1 on 2025-04-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_cart_speacial_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='max_selectable',
            field=models.PositiveIntegerField(default=1, verbose_name='Max Selection'),
        ),
    ]
