# Generated by Django 5.1.1 on 2025-04-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_addon_max_selectable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Vehicle No'),
        ),
    ]
