# Generated by Django 5.2 on 2025-06-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_cart_vehicle_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('DISCOUNT_TYPE_UNSPCIFIED', 'DISCOUNT_TYPE_UNSPCIFIED'), ('DISCOUNT_TYPE_PERCENTAGE', 'DISCOUNT_TYPE_PERCENTAGE'), ('DISCOUNT_TYPE_FIXED', 'DISCOUNT_TYPE_FIXED')], default='DISCOUNT_TYPE_PERCENTAGE', max_length=30),
        ),
    ]
