# Generated by Django 5.2 on 2025-06-13 16:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_coupon_discount_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSession',
            fields=[
                ('service_session_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('service_status', models.CharField(choices=[('SERVICE_SESSION_UNSPECIFIED', 'Service Session Unspecified'), ('SERVICE_SESSION_PENDING', 'Service Session Pending'), ('SERVICE_SESSION_ONGOING', 'Service Session Ongoing'), ('SERVICE_SESSION_ENDED', 'Service Session Ended'), ('SERVICE_SESSION_CANCELLED', 'Service Session Cancelled')], db_index=True, default='SERVICE_SESSION_ONGOING', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_phone_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='cart',
            name='service_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='api.servicesession'),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_uuid', models.UUIDField(db_index=True)),
                ('table_number', models.CharField(db_index=True, max_length=10)),
                ('area_name', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_type', models.CharField(choices=[('UNSPECIFIED', 'Unspecified'), ('POSTPAID', 'Postpaid'), ('PREPAID', 'Prepaid')], default='POSTPAID', max_length=20)),
                ('no_of_sitting', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['store_uuid', 'table_number'], name='api_table_store_u_36a404_idx')],
                'unique_together': {('store_uuid', 'table_number')},
            },
        ),
        migrations.AddField(
            model_name='servicesession',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.table'),
        ),
        migrations.AddField(
            model_name='cart',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='api.table'),
        ),
    ]
