# Generated by Django 5.2 on 2025-06-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_servicesession_alter_cart_user_phone_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='table_no',
        ),
    ]
