# Generated by Django 5.2 on 2025-06-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_cart_table_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='no_of_sitting',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
