# Generated by Django 5.2 on 2025-06-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_table_no_of_sitting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='payment_type',
            field=models.CharField(choices=[('PAYMENT_TYPE_UNSPECIFIED', 'Payment Type Unspecified'), ('PAYMENT_TYPE_POSTPAID', 'Payment Type Postpaid'), ('PAYMENT_TYPE_PREPAID', 'Payment Type Prepaid')], default='PAYMENT_TYPE_POSTPAID', max_length=20),
        ),
    ]
