# Generated by Django 5.2 on 2025-06-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_table_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesession',
            name='service_status',
            field=models.CharField(choices=[('SERVICE_SESSION_UNSPECIFIED', 'Service Session Unspecified'), ('SERVICE_SESSION_PENDING', 'Service Session Pending'), ('SERVICE_SESSION_ONGOING', 'Service Session Ongoing'), ('SERVICE_SESSION_ENDED', 'Service Session Ended'), ('SERVICE_SESSION_CANCELLED', 'Service Session Cancelled')], db_index=True, default='SERVICE_SESSION_ONGOING', max_length=30),
        ),
    ]
