# Generated by Django 5.2 on 2025-06-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_servicesession_service_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='servicesession',
            constraint=models.UniqueConstraint(condition=models.Q(('service_status', 'SERVICE_SESSION_ONGOING')), fields=('table',), name='unique_ongoing_session_per_table'),
        ),
    ]
