# Generated by Django 5.2 on 2025-06-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_servicesession_unique_ongoing_session_per_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicesession',
            options={'ordering': ['started_at']},
        ),
        migrations.AddIndex(
            model_name='servicesession',
            index=models.Index(fields=['table'], name='api_service_table_i_92bec2_idx'),
        ),
    ]
