# Generated by Django 5.2 on 2025-06-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_servicesession_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_type',
            field=models.CharField(choices=[('PAYMENT_TYPE_UNSPECIFIED', 'Payment Type Unspecified'), ('PAYMENT_TYPE_POSTPAID', 'Payment Type Postpaid'), ('PAYMENT_TYPE_PREPAID', 'Payment Type Prepaid')], default='PAYMENT_TYPE_PREPAID', max_length=30, verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='order_type',
            field=models.CharField(choices=[('ORDER_TYPE_UNSPECIFIED', 'Unspecified'), ('ORDER_TYPE_DINE_IN', 'Dine-In'), ('ORDER_TYPE_TAKE_AWAY', 'Takeaway'), ('ORDER_TYPE_DRIVE_THRU', 'Drive-Thru')], default='ORDER_TYPE_DINE_IN', max_length=30),
        ),
        migrations.AlterField(
            model_name='cart',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='state',
            field=models.CharField(choices=[('CART_STATE_UNSPECIFIED_STATE', 'Unspecified'), ('CART_STATE_ACTIVE', 'Active'), ('CART_STATE_LOCKED', 'Locked'), ('CART_STATE_ABANDONED', 'Abandoned')], default='CART_STATE_ACTIVE', max_length=30),
        ),
        migrations.AlterField(
            model_name='cart',
            name='vehicle_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
