# Generated by Django 5.2 on 2025-06-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_cart_payment_type_alter_cart_coupon_code_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cart',
            name='api_cart_store_u_d9705b_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='api_cartite_product_8550e2_idx',
        ),
        migrations.RemoveIndex(
            model_name='couponusage',
            name='api_couponu_user_ph_2b988a_idx',
        ),
        migrations.RenameIndex(
            model_name='addon',
            new_name='idx_addon_cart_item',
            old_name='api_addon_cart_it_8c6aff_idx',
        ),
        migrations.RenameIndex(
            model_name='addon',
            new_name='idx_addon_uuid',
            old_name='api_addon_add_on__c47b86_idx',
        ),
        migrations.RenameIndex(
            model_name='cartitem',
            new_name='idx_cart',
            old_name='api_cartite_cart_id_516016_idx',
        ),
        migrations.AddIndex(
            model_name='addon',
            index=models.Index(fields=['cart_item', 'add_on_uuid'], name='idx_addon_cart_item_uuid'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['store_uuid', 'user_phone_no'], name='api_cart_store_u_edd9e7_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['cart_uuid'], name='api_cart_cart_uu_62ba38_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['service_session'], name='api_cart_service_247dab_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['state'], name='api_cart_state_346d67_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['payment_type'], name='api_cart_payment_56ab41_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['product_uuid'], name='idx_product_uuid'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart_item_uuid'], name='idx_cart_item_uuid'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product_uuid'], name='idx_cart_product_uuid'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon'], name='idx_coupon'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['user_phone_no'], name='idx_user_phone_no'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['cart_uuid'], name='idx_cart_uuid'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon', 'user_phone_no', 'cart_uuid'], name='idx_coupon_user_cart'),
        ),
    ]
