# Generated by Django 5.1.1 on 2025-02-19 09:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('to_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('from_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('message_json', models.JSONField(default=dict)),
                ('rendered_message', models.JSONField(default=dict)),
                ('variables', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='template.template')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('to_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('from_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('message_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('rendered_message', models.JSONField(default=dict)),
                ('variables', models.JSONField(default=dict)),
                ('message_type', models.CharField(blank=True, choices=[('MARKETING', 'Marketing'), ('UTILITY', 'Utility'), ('AUTHENTICATION', 'Authentication')], max_length=20, null=True)),
                ('priority', models.IntegerField(choices=[(1, 'Marketing'), (2, 'Utility'), (3, 'Authentication')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='template.template')),
            ],
            options={
                'ordering': ['priority', 'status', '-created_at'],
                'indexes': [models.Index(fields=['priority', 'status'], name='message_ser_priorit_46fd1c_idx')],
            },
        ),
    ]
