# Generated by Django 5.1.1 on 2025-02-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invalidmessage',
            name='template_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
