# Generated by Django 5.1.1 on 2025-02-19 09:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('HEADER', 'Header'), ('BODY', 'Body'), ('FOOTER', 'Footer')], max_length=255)),
                ('format', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('MARKETING', 'Marketing'), ('UTILITY', 'Utility'), ('AUTHENTICATION', 'Authentication')], max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('parameter_format', models.CharField(choices=[('POSITIONAL', 'Positional'), ('NAMED', 'Named')], default='POSITIONAL', max_length=255)),
                ('message_send_ttl_seconds', models.IntegerField(default=86400)),
                ('whatsapp_template_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('TEXT', 'Text'), ('URL', 'URL'), ('CURRENCY', 'Currency'), ('MEDIA', 'Media')], max_length=255)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='template.component')),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameters',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='component',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='template.template'),
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('QUICK_REPLY', 'Quick Reply'), ('URL', 'URL')], max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='template.template')),
            ],
            options={
                'indexes': [models.Index(fields=['template', 'index'], name='template_bu_templat_e601b2_idx')],
            },
        ),
    ]
