# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: healthcheck.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'healthcheck.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import annotations_pb2 as annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11healthcheck.proto\x12\x0egrpc.health.v1\x1a\x11\x61nnotations.proto\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\x94\x01\n\x13HealthCheckResponse\x12\x41\n\x06status\x18\x01 \x01(\x0e\x32\x31.grpc.health.v1.HealthCheckResponse.ServingStatus\":\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x32\xbf\x01\n\x06Health\x12\x61\n\x05\x43heck\x12\".grpc.health.v1.HealthCheckRequest\x1a#.grpc.health.v1.HealthCheckResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\x07/health\x12R\n\x05Watch\x12\".grpc.health.v1.HealthCheckRequest\x1a#.grpc.health.v1.HealthCheckResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'healthcheck_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTH'].methods_by_name['Check']._loaded_options = None
  _globals['_HEALTH'].methods_by_name['Check']._serialized_options = b'\202\323\344\223\002\t\022\007/health'
  _globals['_HEALTHCHECKREQUEST']._serialized_start=56
  _globals['_HEALTHCHECKREQUEST']._serialized_end=93
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=96
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=244
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_start=186
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_end=244
  _globals['_HEALTH']._serialized_start=247
  _globals['_HEALTH']._serialized_end=438
# @@protoc_insertion_point(module_scope)
