# Generated by Django 5.2 on 2025-06-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
